### ISSUE TITLE
Cannot plot single samples for 96 mutation profile

### ISSUE THREAD

**Issue by liggettla** [UMCUGenetics/MutationalPatterns#12]
Perhaps I am misinterpreting the analysis, but when using this:   
`plot_96_profile(mut_mat[,c(1,2)])`   
it should be possible to just plot a single sample because there is no multiple sample comparison being made.  
But when I try to plot only a single sample like this:  
`plot_96_profile(mut_mat[,c(1)])`  
I receive the following error:  
`Error in apply(mut_matrix, 2, function(x) x/sum(x)) : dim(X) must have a positive length`

**Comment by roelj** [comment]
Hello @liggettla 

Thanks for also reporting this problem.  I have been able to reproduce your problem, and I am working on a bugfix.

**Comment by roelj** [comment]
So, when only a single column is passed as matrix, R converts it to a vector.  To prevent R from doing this, you could add `drop=FALSE` to the mut_mat[], like so:
```{r}
plot_96_profile(mut_mat[,c(1), drop=FALSE])
```

I hope this helps.

**Comment by liggettla** [comment]
Glad to help. Otherwise your suggested quick fix works, thanks.

**Comment by roelj** [comment]
Since we lose the sample name when it is converted to a vector, there's no way to recover from it inside the function.  Therefore, the only thing we can do is add some documentation about it to the function.

Thanks for your report.  I consider this solved, because there's not going to be a better technical solution than preventing the conversion to a vector.

Thanks again!  I really appreciate the time you take for reporting these things.
