### ISSUE TITLE
Axis lable offsets

### ISSUE THREAD

**Issue by sternp** [UMCUGenetics/MutationalPatterns#52]
The axis labels aren't properly centered for a few of the graph commands. I've noticed it for heatmaps on the X axis.

A simple tweak to the ggplot code would make it more user friendly.

Overall, thanks for this pretty neat package!

**Comment by FreekManders** [comment]
Hi Sternp, thank you for bringing this to our attention. The issue seems to be caused by this: https://github.com/tidyverse/ggplot2/issues/1878

I fixed it in the newest development version by adding `vjust = 0.5`, to all x-axes with a 90-degree angle.
The fix can be found here: https://github.com/FreekManders/MutationalPatterns/commit/de319463ce8b580dff095fc44b30cb9e58381ce1
If you haven't done it already, you could probably add this to your heatmaps to fix them: `fig = fig + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 8))` (Might not work if you use the dendograms).
