### ISSUE TITLE
Binomial test p value

### ISSUE THREAD

**Issue by FrancisBlokzijl** [UMCUGenetics/MutationalPatterns#54]
Hi Freek,

The bionomial test in this package was meant as one-tailed test, you either test for a depletion or an enrichment (not both). As described in the function description.

Now I see you've added code to make it two-sided? This is not in line with the function description and would also mean that people that have been using this function will get a different p-value when they update to a new version of mutationalpatterns, right? This should be avoided. What you could do is add a third option so you have: "enrichment" "depletion" or "two-tailed". This way people will get the same results, but two-sided is now also an option.

Best,
Francis

**Comment by FreekManders** [comment]
Hi Francis,

Whether the function tests for enrichment or depletion depends on whether the observed number of mutations is higher or lower than expected. The test that is used is thus dependent on the data. This means that a user is effectively always testing for both enrichment and depletion. (This was already the case in the previous version of the package). Therefore, the test has to be two-sided. A one-sided test would only be allowed if the user determined beforehand whether or not to test for either depletion or enrichment, independent of the data.
Because the previous result was, in my opinion, incorrect, I felt that it was better to change the resulting p-value, instead of keeping the old results.
