### ISSUE TITLE
Installation with Conda

### ISSUE THREAD

**Issue by kevwilhelm95** [UMCUGenetics/MutationalPatterns#57]
I'm trying to install the package to use on a server but the installation stalls at "Solving Environment". It seems like there are package conflicts with other installed packages. Using version 4.0.3 and installed using "conda install -c conda-forge r-base".

 Any help would be much appreciated.

**Comment by kevwilhelm95** [comment]
I wasn't able to install with conda but opening R and installing the packages worked for me

**Comment by pdiakumis** [comment]
@kevwilhelm95 I'd recommend giving mamba (https://github.com/mamba-org/mamba) a go if you see that 'Solving Environments' take too long. It's super quick.
Basically you use `mamba install` in place of `conda install`. I would avoid installing R packages directly through an R session inside a conda environment since that can cause issues (speaking from many unpleasant experiences).

**Comment by FreekManders** [comment]
Hi @kevwilhelm95,
I'm glad to hear you managed to install the package. 
In case you want to install the package with conda in the future this info might be useful: Conda by default looks in the system R libraries instead of the ones installed by conda, when a system R installation exists. Changing some settings file to force conda's R to use its own library solved a similar issue I had in the past.
