### ISSUE TITLE
Single strand mutational signatures

### ISSUE THREAD

**Issue by gevro** [UMCUGenetics/MutationalPatterns#71]
Is there a way to run mutational signature analysis on single-stranded mutations? I'm not referring to transcriptional or replication bias, but to single-stranded mutations. This would require mut_context to know which strand the mutation is on based on a strand field in the input VCF and to derive the context accordingly.

**Comment by FreekManders** [comment]
I'm not entirely sure I understand what you mean. When a nucleotide on one strand is mutated, for example from a C to a T, then during cell division an A will be placed opposite the T in one of the daughter cells. When you then perform whole genome sequencing, you don't know on which strand the mutation is located. Are you using some sort of single strand sequencing technology, instead of whole genome or whole exome sequencing?

**Comment by gevro** [comment]
Exactly - I'm using a type of library prep that preserves strand information. So I know which strand is mutated. If this isn't easily possible, that's fine, but it would be nice if there is some way to do this?

**Comment by FreekManders** [comment]
I don't think this is very easily possible, because the package considers a G>A mutation and a C>T mutation as the same thing. The easiest solution for substitutions would probably be to split the mutations with a C/T and a G/A reference in separate samples. By creating separate plots for these mutations, you preserve the distinction between them.

**Comment by gevro** [comment]
Thanks for the suggestion. Can you clarify a bit more what you mean by? Do you mean that I could manually separate the reverse complements from each other, and then use MutationalPatterns? Wouldn't MutationalPatterns still revert them back to just one strand? Does MutationalPatterns have a plotting function where it doesn't collapse the variants to one of the two reverse complements?

**Comment by FreekManders** [comment]
MutationalPatterns will treat G>A and C>T as being the same. However, you could split them in separate samples and create separate plots. This way MutationalPatterns can't collapse them.

**Comment by gevro** [comment]
Ok I will try.
