### ISSUE TITLE
Order of samples in plots

### ISSUE THREAD

**Issue by MyrtheJ** [UMCUGenetics/MutationalPatterns#9]
Hello!

I would like to be able to change the order of some of the plots manually (e.g. plot_spectrum, plot_strand and plot_strand_bias). Currently, the plots are automatically sorted alphabetically based on "by = xxx". 

For instance, if you have 2 types: WT and MUT and you want to plot the spectrum:
type <- c("WT","MUT")
plot_spectrum(type_occurences, by = type, legend = T)
It will automatically plot the "MUT" samples first/left, but I want to plot the "WT" samples first/left.

Is it in any way possible to do this? Or can you add this feature?

Myrthe

**Comment by FrancisBlokzijl** [comment]
Hey Myrthe,

Yes, because the package uses ggplot2 for plotting, it is automatically alphabetically sorted.

You can work around this by changing your **character vector** into a **factor** and setting the order of the levels, like this:

type <- c("WT", "WT", "MUT", "MUT")
order <- c("WT", "MUT")
type <- factor(type, levels = order)

Now it will plot the samples in your preferred order.

Let me know if this works for you!

Best,
Francis

**Comment by MyrtheJ** [comment]
Thank you! This seems to work.

Best, 
Myrthe
